# Generated by Django 5.2.15 on 2026-06-24 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pagina_pessoal', models.URLField(help_text='Ligação para a página pessoal no site da Universidade Lusófona.')),
                ('fotografia', models.ImageField(blank=True, upload_to='docentes/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
                ('codigo', models.CharField(help_text='Código usado pela instituição (por exemplo, 260 para LEI).', max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('duracao_semestres', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ects', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('website', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='licenciaturas/')),
            ],
            options={
                'verbose_name': 'licenciatura',
                'verbose_name_plural': 'licenciaturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30)),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('ects', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='unidades_curriculares/')),
                ('docentes', models.ManyToManyField(blank=True, related_name='unidades_curriculares', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_curriculares', to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'unidade curricular',
                'verbose_name_plural': 'unidades curriculares',
                'ordering': ['licenciatura', 'ano', 'semestre', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('licenciatura', 'codigo'), name='uc_codigo_unico_por_licenciatura')],
            },
        ),
    ]
