# Generated by Django 5.2.15 on 2026-06-24 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('tecnica', 'Técnica'), ('interpessoal', 'Interpessoal'), ('linguistica', 'Linguística'), ('outra', 'Outra')], max_length=20)),
                ('descricao', models.TextField()),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=15)),
            ],
            options={
                'verbose_name': 'competência',
                'verbose_name_plural': 'competências',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem de programação'), ('framework', 'Framework'), ('base_dados', 'Base de dados'), ('ferramenta', 'Ferramenta'), ('plataforma', 'Plataforma'), ('outra', 'Outra')], max_length=20)),
                ('descricao', models.TextField()),
                ('logo', models.ImageField(upload_to='tecnologias/')),
                ('website', models.URLField(help_text='Website oficial da tecnologia.')),
                ('interesse', models.PositiveSmallIntegerField(help_text='Classificação pessoal entre 1 e 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=15)),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('curso', 'Curso'), ('certificacao', 'Certificação'), ('workshop', 'Workshop'), ('outra', 'Outra')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('em_curso', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('certificado', models.FileField(blank=True, upload_to='formacoes/certificados/')),
                ('url', models.URLField(blank=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.competencia')),
            ],
            options={
                'verbose_name': 'formação',
                'verbose_name_plural': 'formações',
                'ordering': ['-data_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('conceitos_aplicados', models.TextField(help_text='Conceitos das unidades curriculares aplicados no projeto.')),
                ('data', models.DateField()),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('github_url', models.URLField(verbose_name='repositório GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='demonstração')),
                ('video_url', models.URLField(blank=True, verbose_name='vídeo')),
                ('destaque', models.BooleanField(default=False)),
                ('unidades_curriculares', models.ManyToManyField(related_name='projetos', to='portfolio.unidadecurricular')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-data', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia'),
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('estudante', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, verbose_name='ligação externa')),
                ('interesse', models.PositiveSmallIntegerField(help_text='Classificação pessoal entre 1 e 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('destaque', models.BooleanField(default=False)),
                ('orientadores', models.ManyToManyField(blank=True, related_name='tfcs_orientados', to='portfolio.docente')),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
                'ordering': ['-ano', 'titulo'],
            },
        ),
    ]
