# Generated by Django 5.2.15 on 2026-06-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0002_competencia_tecnologia_formacao_projeto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('data', models.DateField(auto_now_add=True)),
                ('fase', models.CharField(choices=[('modelo', 'Modelação'), ('implementacao', 'Implementação'), ('teste', 'Testes'), ('revisao', 'Revisão')], max_length=20)),
                ('descricao', models.TextField(verbose_name='trabalho realizado')),
                ('decisoes', models.TextField(verbose_name='decisões e justificações')),
                ('erros', models.TextField(blank=True)),
                ('correcoes', models.TextField(blank=True, verbose_name='correções')),
                ('uso_ia', models.TextField(blank=True, help_text='Descrever como a IA contribuiu, ou não, para esta etapa.', verbose_name='utilização de IA')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da entidade documentada')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'app_label': 'portfolio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='tipo de entidade documentada')),
            ],
            options={
                'verbose_name': 'entrada do Making Of',
                'verbose_name_plural': 'entradas do Making Of',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaMakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='makingof/')),
                ('legenda', models.CharField(max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='portfolio.makingof')),
            ],
            options={
                'verbose_name': 'evidência do Making Of',
                'verbose_name_plural': 'evidências do Making Of',
                'ordering': ['entrada', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('entrada', 'ordem'), name='ordem_evidencia_unica_por_entrada')],
            },
        ),
    ]
