# Generated by Django 5.2.15 on 2026-06-24 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_makingof_evidenciamakingof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='número académico')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['nome', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AreaTFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'área de TFC',
                'verbose_name_plural': 'áreas de TFC',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PalavraChaveTFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'palavra-chave de TFC',
                'verbose_name_plural': 'palavras-chave de TFC',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='area',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='estudante',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='url',
        ),
        migrations.AddField(
            model_name='tfc',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tfc',
            name='estado',
            field=models.CharField(choices=[('em_curso', 'Em curso'), ('concluido', 'Concluído')], default='concluido', max_length=15),
        ),
        migrations.AddField(
            model_name='tfc',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='licenciaturas',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.licenciatura'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='parceria',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tfc',
            name='relatorio_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='relatório'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='vídeo'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='pagina_pessoal',
            field=models.URLField(blank=True, help_text='Ligação para a página pessoal no site da Universidade Lusófona.'),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='duracao_semestres',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='ects',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='categoria',
            field=models.CharField(blank=True, choices=[('linguagem', 'Linguagem de programação'), ('framework', 'Framework'), ('base_dados', 'Base de dados'), ('ferramenta', 'Ferramenta'), ('plataforma', 'Plataforma'), ('outra', 'Outra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='interesse',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Classificação pessoal entre 1 e 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='logo',
            field=models.ImageField(blank=True, upload_to='tecnologias/'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='nivel',
            field=models.CharField(blank=True, choices=[('iniciante', 'Iniciante'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='website',
            field=models.URLField(blank=True, help_text='Website oficial da tecnologia.'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='interesse',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Classificação pessoal entre 1 e 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='tfc',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.aluno'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.areatfc'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='palavras_chave',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.palavrachavetfc'),
        ),
        migrations.AddConstraint(
            model_name='tfc',
            constraint=models.UniqueConstraint(fields=('titulo', 'ano', 'email'), name='tfc_titulo_ano_email_unicos'),
        ),
    ]
