# Generated by Django 5.2.15 on 2026-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aluno_areatfc_palavrachavetfc_remove_tfc_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ciencia_vitae',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo_funcionario',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='grau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docente',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='docente',
            name='orcid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='docente',
            name='regime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='acreditacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='area_cientifica',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='competencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='condicoes_acesso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='licenciaturas', to='portfolio.docente'),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='grau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='saidas_profissionais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='ano_letivo',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='apresentacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='avaliacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='competencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='horas_contacto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='idioma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='metodologia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='natureza',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='programa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='unidades_curriculares/'),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='semestre',
            field=models.CharField(choices=[('S1', '1.º semestre'), ('S2', '2.º semestre'), ('A', 'Anual')], max_length=2),
        ),
    ]
