# Generated by Django 5.2.15 on 2026-06-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_docente_ciencia_vitae_docente_codigo_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de tecnologia',
                'verbose_name_plural': 'tipos de tecnologia',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='portfolio.tipotecnologia'),
        ),
    ]
